[common.variables]
copy_command = "pbcopy"  # default/fallback
theme            = "tokyo-night"                # tokyo-night | catppuccin-macchiato | catppuccin-mocha | gruvbox-dark
theme_ghostty    = "TokyoNight"                # Tokyo Night | Catppuccin Macchiato | Catppuccin Mocha | GruvboxDark
theme_wezterm    = "Tokyo Night Storm (Gogh)"   # Tokyo Night Storm (Gogh) | Catppuccin Macchiato (Gogh) | Catppuccin Mocha (Gogh) | GruvboxDark

[common.files]
"common/linters" = "~/.config"
"common/cargo" = "~/.cargo"
"common/fastfetch" = "~/.config/fastfetch"
"common/mise" = "~/.config/mise"
"common/nvim" = "~/.config/nvim"
"common/starship" = "~/.config"
"common/zsh" = "~/.config/zsh"
"common/bash" = "~/.config/bash"
"common/tmux/tmux.conf" = "~/.tmux.conf"
"common/uv" = "~/.config/uv"
"common/claude/settings.json" = "~/.claude/settings.json"
"common/claude/CLAUDE.md" = "~/.claude/CLAUDE.md"
"common/claude/skills/handoff-refresh" = "~/.claude/skills/handoff-refresh"

[windows.files]
"windows/startup/startup.vbs" = "C:\\Users\\2015m\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\startup.vbs"
"windows/komorebi" = "~/.config/komorebi"
"windows/yasb" = "~/.config/yasb"
"windows/nushell" = "~/.config/nushell"
"windows/wezterm/constants.lua" = "~/.config/wezterm/constants.lua"
"windows/wezterm/functions.lua" = "~/.config/wezterm/functions.lua"
"windows/wezterm/keybinds.lua" = "~/.config/wezterm/keybinds.lua"
"windows/wezterm/wezterm.lua" = { target = "~/.config/wezterm/wezterm.lua", type = "template" }
"windows/wsl/.wslconfig" = "~/.wslconfig"

[mac.files]
"common/bottom" = "~/Library/Application Support/bottom"
"macos/borders" = "~/.config/borders"
"macos/aerospace" = "~/.config/aerospace"
"macos/ghostty/config" = { target = "~/.config/ghostty/config", type = "template" }

[linux.files]
"common/bottom" = "~/.config/bottom"
"windows/wsl/.hushlogin" = "~/.hushlogin"
